# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7c88b1b105abb111857e22711c6d202bdd97e6e5f101bec6fa1c78693d44a90251ff5bc27f8e6358a6f19a52a306671ca467d4da553ad7dd1bf35a7afde3530

test:
  secret_key_base: 360962cb3d06076121285452f974ccda330ad5c8e972b1354b5c2ff86112a64c04698cf53bd9a3b176574726e3e1d7d49c52659a1d55fc4770ffd82abd0d58d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
